export const categoryData = [
  {
    id: 0,
    image: '/animals/funnydog.png',
    title: 'пси',
    link: 'psi',
    text: ' ',
    textStyle: 'text-red-900',
    detailsContainer: ['left-4 top-4', 'text-left'],
    background: ['bg-red-400', 'bg-left-bottom'],
    imageStyle: '-left-10',
    imgWidth: 'w-full',
  },
  {
    id: 1,
    image: '/animals/maca.png',
    title: 'мачке',
    link: 'macke',
    text: '',
    textStyle: 'text-yellow-900',
    detailsContainer: ['left-2 top-4', 'text-left'],
    background: ['bg-yellow-400', 'bg-left-bottom'],
    imageStyle: '',
    imgWidth: 'w-full',
  },
  {
    id: 2,
    image: '/animals/papagaj.png',
    title: 'птице',
    link: 'ptice',
    text: '',
    textStyle: 'text-blue-800',
    detailsContainer: ['right-4 top-10', 'text-right'],
    background: ['bg-blue-300', 'bg-right-bottom'],
    imageStyle: '-left-20',
    imgWidth: 'w-full',
  },
  {
    id: 3,
    image: '/animals/zlatna-ribica.png',
    title: 'рибице',
    link: 'ribice',
    text: '',
    textStyle: 'text-blue-900',
    detailsContainer: ['left-4 top-4'],
    background: ['bg-blue-400', 'bg-left-bottom'],
    imageStyle: '-left-20',
    imgWidth: 'w-full',
  },
  {
    id: 4,
    image: '/animals/zec.png',
    title: 'глодари',
    link: 'glodari',
    text: '',
    textStyle: 'text-green-900',
    detailsContainer: ['right-2 top-2', 'text-right'],
    background: ['bg-green-400', 'bg-right-bottom'],
    imageStyle: '-left-10',
    imgWidth: 'w-1/2',
  },
];
