export const categoryData = [
  {
    id: 0,
    image: '/animals/kucov.png',
    title: 'пси',
    link: 'psi',
    text: 'lorem ipsun dolor...',
    textStyle: 'text-red-900',
    detailsContainer: ['left-2 top-6', 'text-left'],
    background: ['bg-red-400', 'bg-left-bottom'],
    imageStyle: '-right-16',
    imgWidth: 'w-full',
  },
  {
    id: 1,
    image: '/animals/macka.png',
    title: 'мачке',
    link: 'macke',
    text: 'lorem ipsun dolor sit emmet...',
    textStyle: 'text-yellow-900',
    detailsContainer: ['right-2 top-4', 'text-right'],
    background: ['bg-yellow-400', 'bg-right-bottom'],
    imageStyle: '-left-16',
    imgWidth: 'w-full',
  },
  {
    id: 2,
    image: '/animals/pticica.png',
    title: 'птице',
    link: 'ptice',
    text: 'lorem ipsun dolor...',
    textStyle: 'text-blue-800',
    detailsContainer: ['right-2 top-2', 'text-right'],
    background: ['bg-blue-300', 'bg-right-bottom'],
    imageStyle: '-left-20',
    imgWidth: 'w-full',
  },
  {
    id: 3,
    image: '/animals/ribica.png',
    title: 'акваристика',
    link: 'akvaristika',
    text: 'lorem ipsun dolor...',
    textStyle: 'text-blue-900',
    detailsContainer: ['left-2 top-3'],
    background: ['bg-blue-400', 'bg-left-bottom'],
    imageStyle: '-right-20',
    imgWidth: 'w-full',
  },
  {
    id: 4,
    image: '/animals/zec.png',
    title: 'мале животиње',
    link: 'male-zivotinje',
    text: 'lorem ipsun dolor...',
    textStyle: 'text-green-900',
    detailsContainer: ['right-2 top-2', 'text-right'],
    background: ['bg-green-400', 'bg-right-bottom'],
    imageStyle: '-left-10',
    imgWidth: 'w-1/2',
  },
];
